;===============================================================================
; Copyright (C) 2013+ by Andrzej Adamczyk at Wataha.net
;===============================================================================

KERNEL_BASE_address					equ	0x00100000

;===============================================================================
; PIT
;===============================================================================
KERNEL_PIT_CLOCK_hz					equ	1000

;===============================================================================
; MEMORY
;===============================================================================
KERNEL_MEMORY_LOW_address				equ	KERNEL_BASE_address
KERNEL_MEMORY_HIGH_address				equ	0xFFFF000000000000
KERNEL_MEMORY_HIGH_REAL_address				equ	0xFFFF800000000000
KERNEL_MEMORY_HIGH_VIRTUAL_address			equ	KERNEL_MEMORY_HIGH_REAL_address - KERNEL_MEMORY_HIGH_address

KERNEL_MEMORY_STACK_KERNEL_SIZE_byte			equ	KERNEL_PAGE_SIZE_byte * WORD_SIZE_byte
KERNEL_MEMORY_STACK_KERNEL_address			equ	KERNEL_MEMORY_HIGH_VIRTUAL_address - KERNEL_MEMORY_STACK_KERNEL_SIZE_byte

;===============================================================================
; PIC
;===============================================================================
KERNEL_PIC_IRQ_SHEDULER					equ	0x00
KERNEL_PIC_IRQ_KEYBOARD					equ	0x01

;===============================================================================
; PAGE
;===============================================================================
KERNEL_PAGE_SIZE_byte					equ	0x1000
KERNEL_PAGE_SIZE_shift					equ	12

KERNEL_PAGE_mask					equ	0xFFFFFFFFFFFFF000

KERNEL_PAGE_FLAG_AVAILABLE				equ	0x01
KERNEL_PAGE_FLAG_WRITE					equ	0x02
KERNEL_PAGE_FLAG_USER					equ	0x04
KERNEL_PAGE_FLAG_WRITE_THROUGH				equ	0x08
KERNEL_PAGE_FLAG_CACHE					equ	0x10
KERNEL_PAGE_FLAG_PAGE_SIZE				equ	0x80

KERNEL_PAGE_ROW_count					equ	512

KERNEL_PAGE_PML4_SIZE_byte				equ	KERNEL_PAGE_ROW_count * KERNEL_PAGE_PML3_SIZE_byte
KERNEL_PAGE_PML3_SIZE_byte				equ	KERNEL_PAGE_ROW_count * KERNEL_PAGE_PML2_SIZE_byte
KERNEL_PAGE_PML2_SIZE_byte				equ	KERNEL_PAGE_ROW_count * KERNEL_PAGE_PML1_SIZE_byte
KERNEL_PAGE_PML1_SIZE_byte				equ	KERNEL_PAGE_ROW_count * KERNEL_PAGE_SIZE_byte

;===============================================================================
; IDT
;===============================================================================
KERNEL_IDT_IRQ_HARDWARE_offset				equ	0x20

KERNEL_IDT_IRQ_SHEDULER					equ	0x00
KERNEL_IDT_IRQ_PS2					equ	0x01

KERNEL_IDT_TYPE_EXCEPTION				equ	0x8E00
KERNEL_IDT_TYPE_IRQ					equ	0x8F00
KERNEL_IDT_TYPE_ISR					equ	0xEF00

;===============================================================================
; TASK
;===============================================================================
KERNEL_TASK_EFLAGS_IF					equ	000000000000001000000000b	; przerwania włączone
KERNEL_TASK_EFLAGS_DEFAULT				equ	KERNEL_TASK_EFLAGS_IF

KERNEL_TASK_FLAG_ACTIVE					equ	0000000000000001b	; rekord bierze czynny udział w pracy systemu
KERNEL_TASK_FLAG_CLOSED					equ	0000000000000010b	; rekord oczkuje na kolekcjonera śmieci
KERNEL_TASK_FLAG_DAEMON					equ	0000000000000100b	; rekord zawiera proces typu daemon
KERNEL_TASK_FLAG_RESERVED				equ	0000000000001000b	; rekord zarezerwowany

KERNEL_TASK_FLAG_ACTIVE_bit				equ	0
KERNEL_TASK_FLAG_CLOSED_bit				equ	1
KERNEL_TASK_FLAG_DAEMON_bit				equ	2
KERNEL_TASK_FALG_RESERVED_bit				equ	3

;===============================================================================
; STAŁE POWSZECHNE
;===============================================================================
ASCII_TERMINATOR					equ	0x00
ASCII_ENTER						equ	0x0D
ASCII_NEW_LINE						equ	0x0A
ASCII_BACKSPACE						equ	0x08
ASCII_TAB						equ	0x09
ASCII_ESCAPE						equ	0x1B
ASCII_SPACE						equ	0x20
ASCII_QUOTA						equ	0x22
ASCII_COMMA						equ	0x2C
ASCII_DOT						equ	0x2E
ASCII_SLASH						equ	0x2F
ASCII_NUMBER						equ	0x30
ASCII_NUMBER_ZERO					equ	0x30
ASCII_NUMBER_NINE					equ	0x39
ASCII_BACKSLASH						equ	0x5C
ASCII_TILDE						equ	0x7E
ASCII_DELETE						equ	0x7F

EMPTY							equ	0
MAX_UNSIGNED						equ	-1

DIVIDE_BY_2_shift					equ	1
DIVIDE_BY_4_shift					equ	2
DIVIDE_BY_8_shift					equ	3
DIVIDE_BY_16_shift					equ	4
DIVIDE_BY_32_shift					equ	5
DIVIDE_BY_64_shift					equ	6
DIVIDE_BY_128_shift					equ	7
DIVIDE_BY_256_shift					equ	8
DIVIDE_BY_512_shift					equ	9
DIVIDE_BY_1024_shift					equ	10
DIVIDE_BY_2048_shift					equ	11
DIVIDE_BY_4096_shift					equ	12
DIVIDE_BY_PAGE_shift					equ	KERNEL_PAGE_SIZE_shift

MULTIPLE_BY_2_shift					equ	1
MULTIPLE_BY_4_shift					equ	2
MULTIPLE_BY_8_shift					equ	3
MULTIPLE_BY_16_shift					equ	4
MULTIPLE_BY_32_shift					equ	5
MULTIPLE_BY_64_shift					equ	6
MULTIPLE_BY_128_shift					equ	7
MULTIPLE_BY_256_shift					equ	8
MULTIPLE_BY_512_shift					equ	9
MULTIPLE_BY_1024_shift					equ	10
MULTIPLE_BY_2048_shift					equ	11
MULTIPLE_BY_4096_shift					equ	12
MULTIPLE_BY_PAGE_shift					equ	KERNEL_PAGE_SIZE_shift

MOVE_HIGH_TO_AL						equ	8
MOVE_HIGH_TO_AX						equ	16
MOVE_HIGH_TO_EAX					equ	32
MOVE_AL_TO_HIGH						equ	8
MOVE_AX_TO_HIGH						equ	16
MOVE_EAX_TO_HIGH					equ	32

REPLACE_EAX_WITH_HIGH					equ	32

QWORD_SIZE_byte						equ	8
DWORD_SIZE_byte						equ	4
WORD_SIZE_byte						equ	2
BYTE_SIZE_byte						equ	1

QWORD_HIGH_move						equ	4
DWORD_HIGH_move						equ	2
WORD_HIGH_move						equ	1

QWORD_BIT_sign						equ	63
DWORD_BIT_sign						equ	31
WORD_BIT_sign						equ	15
BYTE_BIT_sign						equ	7

QWORD_mask_high						equ	0xFFFFFFFF00000000
DWORD_mask						equ	0x00000000FFFFFFFF
WORD_mask						equ	0x000000000000FFFF
BYTE_mask						equ	0x00000000000000FF

TRUE							equ	1
FALSE							equ	0

NUMBER_BINARY_system					equ	2
NUMBER_DECIMAL_system					equ	10
NUMBER_HEXADECIMAL_system				equ	16

SIZE_KiB_byte						equ	1024
SIZE_MiB_byte						equ	SIZE_KiB_byte * 1024
SIZE_GiB_byte						equ	SIZE_MiB_byte * 1024
SIZE_TiB_byte						equ	SIZE_GiB_byte * 1024

PORT_PIC_MASTER_command					equ	0x0020
PORT_PIC_MASTER_data					equ	0x0021
PORT_PIT_CLOCK						equ	0x0036
PORT_PIT_CHANNEL_0_data					equ	0x0040
PORT_PIT_CHANNEL_1_data					equ	0x0041
PORT_PIT_CHANNEL_2_data					equ	0x0042
PORT_PIT_CHANNEL_4_command				equ	0x0043
PORT_PS2_data						equ	0x0060
PORT_PS2_command_or_status				equ	0x0064
PORT_PIC_SLAVE_command					equ	0x00A0
PORT_PIC_SLAVE_data					equ	0x00A1
PORT_PIT_SPEAKER					equ	0x00B6

PIT_CRYSTAL						equ	1193182	; Hz

PIC_IRQ_ACCEPT						equ	0x20

PCI_REGISTER_VENDOR_AND_DEVICE				equ	0x00
PCI_REGISTER_STATUS_AND_COMMAND				equ	0x04
PCI_REGISTER_CLASS_AND_SUBCLASS				equ	0x08
PCI_REGISTER_BAR_FLAG_64				equ	2
PCI_REGISTER_BAR0					equ	0x10
PCI_REGISTER_BAR1					equ	0x14
PCI_REGISTER_BAR2					equ	0x18
PCI_REGISTER_BAR3					equ	0x1C
PCI_REGISTER_BAR4					equ	0x20
PCI_REGISTER_BAR5					equ	0x24
PCI_REGISTER_IRQ					equ	0x3C

NETWORK_MAC_mask					equ	0x0000FFFFFFFFFFFF

NETWORK_FRAME_ETHERNET_SIZE_TARGET			equ	0x06
NETWORK_FRAME_ETHERNET_SIZE_SENDER			equ	0x06
NETWORK_FRAME_ETHERNET_SIZE_TYPE			equ	0x02
NETWORK_FRAME_ETHERNET_SIZE				equ	NETWORK_FRAME_ETHERNET_SIZE_TARGET + NETWORK_FRAME_ETHERNET_SIZE_SENDER + NETWORK_FRAME_ETHERNET_SIZE_TYPE
NETWORK_FRAME_ETHERNET_FIELD_TARGET			equ	0x00
NETWORK_FRAME_ETHERNET_FIELD_SENDER			equ	NETWORK_FRAME_ETHERNET_FIELD_TARGET + NETWORK_FRAME_ETHERNET_SIZE_TARGET
NETWORK_FRAME_ETHERNET_FIELD_TYPE			equ	NETWORK_FRAME_ETHERNET_FIELD_SENDER + NETWORK_FRAME_ETHERNET_SIZE_SENDER
NETWORK_FRAME_ETHERNET_FIELD_TYPE_ARP			equ	0x0608
NETWORK_FRAME_ETHERNET_FIELD_TYPE_IP			equ	0x0008

NETWORK_FRAME_ARP_SIZE_HTYPE				equ	0x02
NETWORK_FRAME_ARP_SIZE_PTYPE				equ	0x02
NETWORK_FRAME_ARP_SIZE_HAL				equ	0x01
NETWORK_FRAME_ARP_SIZE_PAL				equ	0x01
NETWORK_FRAME_ARP_SIZE_OPCODE				equ	0x02
NETWORK_FRAME_ARP_SIZE_SENDER_MAC			equ	0x06
NETWORK_FRAME_ARP_SIZE_SENDER_IP			equ	0x04
NETWORK_FRAME_ARP_SIZE_TARGET_MAC			equ	0x06
NETWORK_FRAME_ARP_SIZE_TARGET_IP			equ	0x04
NETWORK_FRAME_ARP_SIZE					equ	NETWORK_FRAME_ARP_SIZE_HTYPE + NETWORK_FRAME_ARP_SIZE_PTYPE + NETWORK_FRAME_ARP_SIZE_HAL + NETWORK_FRAME_ARP_SIZE_PAL + NETWORK_FRAME_ARP_SIZE_OPCODE + NETWORK_FRAME_ARP_SIZE_SENDER_MAC + NETWORK_FRAME_ARP_SIZE_SENDER_IP + NETWORK_FRAME_ARP_SIZE_TARGET_MAC + NETWORK_FRAME_ARP_SIZE_TARGET_IP
NETWORK_FRAME_ARP_FIELD_HTYPE				equ	0x00
NETWORK_FRAME_ARP_FIELD_HTYPE_ETHERNET			equ	0x0100	; 0x0001
NETWORK_FRAME_ARP_FIELD_PTYPE				equ	NETWORK_FRAME_ARP_FIELD_HTYPE + NETWORK_FRAME_ARP_SIZE_HTYPE
NETWORK_FRAME_ARP_FIELD_PTYPE_IPV4			equ	0x0008	; 0x0800
NETWORK_FRAME_ARP_FIELD_HAL				equ	NETWORK_FRAME_ARP_FIELD_PTYPE + NETWORK_FRAME_ARP_SIZE_PTYPE
NETWORK_FRAME_ARP_FIELD_HAL_MAC				equ	0x06	; xx:xx:xx:xx:xx:xx
NETWORK_FRAME_ARP_FIELD_PAL				equ	NETWORK_FRAME_ARP_FIELD_HAL + NETWORK_FRAME_ARP_SIZE_HAL
NETWORK_FRAME_ARP_FIELD_PAL_IPV4			equ	0x04	; x.x.x.x
NETWORK_FRAME_ARP_FIELD_OPCODE				equ	NETWORK_FRAME_ARP_FIELD_PAL + NETWORK_FRAME_ARP_SIZE_PAL
NETWORK_FRAME_ARP_FIELD_OPCODE_REQUEST			equ	0x0100
NETWORK_FRAME_ARP_FIELD_OPCODE_REPLY			equ	0x0200
NETWORK_FRAME_ARP_FIELD_SENDER_MAC			equ	NETWORK_FRAME_ARP_FIELD_OPCODE + NETWORK_FRAME_ARP_SIZE_OPCODE
NETWORK_FRAME_ARP_FIELD_SENDER_IP			equ	NETWORK_FRAME_ARP_FIELD_SENDER_MAC + NETWORK_FRAME_ARP_SIZE_SENDER_MAC
NETWORK_FRAME_ARP_FIELD_TARGET_MAC			equ	NETWORK_FRAME_ARP_FIELD_SENDER_IP + NETWORK_FRAME_ARP_SIZE_SENDER_IP
NETWORK_FRAME_ARP_FIELD_TARGET_IP			equ	NETWORK_FRAME_ARP_FIELD_TARGET_MAC + NETWORK_FRAME_ARP_SIZE_TARGET_MAC

NETWORK_FRAME_IP_SIZE_VERSION_AND_IHL			equ	0x01
NETWORK_FRAME_IP_SIZE_DSCP_AND_ECN			equ	0x01
NETWORK_FRAME_IP_SIZE_TOTAL_LENGTH			equ	0x02
NETWORK_FRAME_IP_SIZE_IDENTIFICATION			equ	0x02
NETWORK_FRAME_IP_SIZE_FLAGS_AND_FRAGMENT_OFFSET		equ	0x02
NETWORK_FRAME_IP_SIZE_TTL				equ	0x01
NETWORK_FRAME_IP_SIZE_PROTOCOL				equ	0x01
NETWORK_FRAME_IP_SIZE_HEADER_CHECKSUM			equ	0x02
NETWORK_FRAME_IP_SIZE_SOURCE_ADDRESS			equ	0x04
NETWORK_FRAME_IP_SIZE_TARGET_ADDRESS			equ	0x04
NETWORK_FRAME_IP_SIZE					equ	NETWORK_FRAME_IP_SIZE_VERSION_AND_IHL + NETWORK_FRAME_IP_SIZE_DSCP_AND_ECN + NETWORK_FRAME_IP_SIZE_TOTAL_LENGTH + NETWORK_FRAME_IP_SIZE_IDENTIFICATION + NETWORK_FRAME_IP_SIZE_FLAGS_AND_FRAGMENT_OFFSET + NETWORK_FRAME_IP_SIZE_TTL + NETWORK_FRAME_IP_SIZE_PROTOCOL + NETWORK_FRAME_IP_SIZE_HEADER_CHECKSUM + NETWORK_FRAME_IP_SIZE_SOURCE_ADDRESS + NETWORK_FRAME_IP_SIZE_TARGET_ADDRESS
NETWORK_FRAME_IP_FIELD_VERSION_AND_IHL			equ	0x00
NETWORK_FRAME_IP_FIELD_DSCP_AND_ECN			equ	NETWORK_FRAME_IP_FIELD_VERSION_AND_IHL + NETWORK_FRAME_IP_SIZE_VERSION_AND_IHL
NETWORK_FRAME_IP_FIELD_TOTAL_LENGTH			equ	NETWORK_FRAME_IP_FIELD_DSCP_AND_ECN + NETWORK_FRAME_IP_SIZE_DSCP_AND_ECN
NETWORK_FRAME_IP_FIELD_IDENTIFICATION			equ	NETWORK_FRAME_IP_FIELD_TOTAL_LENGTH + NETWORK_FRAME_IP_SIZE_TOTAL_LENGTH
NETWORK_FRAME_IP_FIELD_FLAGS_AND_FRAGMENT_OFFSET	equ	NETWORK_FRAME_IP_FIELD_IDENTIFICATION + NETWORK_FRAME_IP_SIZE_IDENTIFICATION
NETWORK_FRAME_IP_FIELD_TTL				equ	NETWORK_FRAME_IP_FIELD_FLAGS_AND_FRAGMENT_OFFSET + NETWORK_FRAME_IP_SIZE_FLAGS_AND_FRAGMENT_OFFSET
NETWORK_FRAME_IP_FIELD_PROTOCOL				equ	NETWORK_FRAME_IP_FIELD_TTL + NETWORK_FRAME_IP_SIZE_TTL
NETWORK_FRAME_IP_FIELD_PROTOCOL_ICMP			equ	0x01
NETWORK_FRAME_IP_FIELD_PROTOCOL_TCP			equ	0x06
NETWORK_FRAME_IP_FIELD_HEADER_CHECKSUM			equ	NETWORK_FRAME_IP_FIELD_PROTOCOL + NETWORK_FRAME_IP_SIZE_PROTOCOL
NETWORK_FRAME_IP_FIELD_SOURCE_ADDRESS			equ	NETWORK_FRAME_IP_FIELD_HEADER_CHECKSUM + NETWORK_FRAME_IP_SIZE_HEADER_CHECKSUM
NETWORK_FRAME_IP_FIELD_TARGET_ADDRESS			equ	NETWORK_FRAME_IP_FIELD_SOURCE_ADDRESS + NETWORK_FRAME_IP_SIZE_SOURCE_ADDRESS
NETWORK_FRAME_IP_FIELD_OPTIONS				equ	NETWORK_FRAME_IP_FIELD_TARGET_ADDRESS + NETWORK_FRAME_IP_SIZE_TARGET_ADDRESS

NETWORK_FRAME_ICMP_SIZE_TYPE				equ	0x01
NETWORK_FRAME_ICMP_SIZE_CODE				equ	0x01
NETWORK_FRAME_ICMP_SIZE_CHECKSUM			equ	0x02
NETWORK_FRAME_ICMP_FIELD_TYPE				equ	0x00
NETWORK_FRAME_ICMP_FIELD_TYPE_PING			equ	0x08
NETWORK_FRAME_ICMP_FIELD_TYPE_REPLY			equ	0x00
NETWORK_FRAME_ICMP_FIELD_CODE				equ	NETWORK_FRAME_ICMP_FIELD_TYPE + NETWORK_FRAME_ICMP_SIZE_TYPE
NETWORK_FRAME_ICMP_FIELD_CHECKSUM			equ	NETWORK_FRAME_ICMP_FIELD_CODE + NETWORK_FRAME_ICMP_SIZE_CODE
NETWORK_FRAME_ICMP_FIELD_DATA				equ	NETWORK_FRAME_ICMP_FIELD_CHECKSUM + NETWORK_FRAME_ICMP_SIZE_CHECKSUM

NETWORK_FRAME_TCP_SIZE_SOURCE_PORT			equ	0x02
NETWORK_FRAME_TCP_SIZE_DESTINATION_PORT			equ	0x02
NETWORK_FRAME_TCP_SIZE_SEQUENCE_NUMBER			equ	0x04
NETWORK_FRAME_TCP_SIZE_ACKNOWLEDGEMENT_NUMBER		equ	0x04
NETWORK_FRAME_TCP_SIZE_HEADER_LENGTH			equ	0x01
NETWORK_FRAME_TCP_SIZE_FLAGS				equ	0x01
NETWORK_FRAME_TCP_SIZE_WINDOW_SIZE			equ	0x02
NETWORK_FRAME_TCP_SIZE_CHECKSUM				equ	0x02
NETWORK_FRAME_TCP_SIZE_URGENT_POINTER			equ	0x02
NETWORK_FRAME_TCP_SIZE_OPTIONS				equ	0x04
NETWORK_FRAME_TCP_SIZE					equ	NETWORK_FRAME_TCP_SIZE_SOURCE_PORT + NETWORK_FRAME_TCP_SIZE_DESTINATION_PORT + NETWORK_FRAME_TCP_SIZE_SEQUENCE_NUMBER + NETWORK_FRAME_TCP_SIZE_ACKNOWLEDGEMENT_NUMBER + NETWORK_FRAME_TCP_SIZE_HEADER_LENGTH + NETWORK_FRAME_TCP_SIZE_FLAGS + NETWORK_FRAME_TCP_SIZE_WINDOW_SIZE + NETWORK_FRAME_TCP_SIZE_CHECKSUM + NETWORK_FRAME_TCP_SIZE_URGENT_POINTER
NETWORK_FRAME_TCP_FIELD_SOURCE_PORT			equ	0x00
NETWORK_FRAME_TCP_FIELD_DESTINATION_PORT		equ	NETWORK_FRAME_TCP_SIZE_SOURCE_PORT
NETWORK_FRAME_TCP_FIELD_SEQUENCE_NUMBER			equ	NETWORK_FRAME_TCP_FIELD_DESTINATION_PORT + NETWORK_FRAME_TCP_SIZE_DESTINATION_PORT
NETWORK_FRAME_TCP_FIELD_ACKNOWLEDGEMENT_NUMBER		equ	NETWORK_FRAME_TCP_FIELD_SEQUENCE_NUMBER + NETWORK_FRAME_TCP_SIZE_SEQUENCE_NUMBER
NETWORK_FRAME_TCP_FIELD_HEADER_LENGTH			equ	NETWORK_FRAME_TCP_FIELD_ACKNOWLEDGEMENT_NUMBER + NETWORK_FRAME_TCP_SIZE_ACKNOWLEDGEMENT_NUMBER
NETWORK_FRAME_TCP_FIELD_HEADER_LENGTH_DEFAULT		equ	0x50	; 5 * 4(32 bits) = 20 B header size
NETWORK_FRAME_TCP_FIELD_FLAGS				equ	NETWORK_FRAME_TCP_FIELD_HEADER_LENGTH + NETWORK_FRAME_TCP_SIZE_HEADER_LENGTH
NETWORK_FRAME_TCP_FIELD_FLAGS_FIN			equ	00000001b
NETWORK_FRAME_TCP_FIELD_FLAGS_SYN			equ	00000010b
NETWORK_FRAME_TCP_FIELD_FLAGS_RST			equ	00000100b
NETWORK_FRAME_TCP_FIELD_FLAGS_PSH			equ	00001000b
NETWORK_FRAME_TCP_FIELD_FLAGS_ACK			equ	00010000b
NETWORK_FRAME_TCP_FIELD_FLAGS_URG			equ	00100000b
NETWORK_FRAME_TCP_FIELD_WINDOW_SIZE			equ	NETWORK_FRAME_TCP_FIELD_FLAGS + NETWORK_FRAME_TCP_SIZE_FLAGS
NETWORK_FRAME_TCP_FIELD_CHECKSUM			equ	NETWORK_FRAME_TCP_FIELD_WINDOW_SIZE + NETWORK_FRAME_TCP_SIZE_WINDOW_SIZE
NETWORK_FRAME_TCP_FIELD_URGENT_POINTER			equ	NETWORK_FRAME_TCP_FIELD_CHECKSUM + NETWORK_FRAME_TCP_SIZE_CHECKSUM
NETWORK_FRAME_TCP_FIELD_OPTIONS				equ	NETWORK_FRAME_TCP_FIELD_URGENT_POINTER + NETWORK_FRAME_TCP_SIZE_URGENT_POINTER
NETWORK_FRAME_TCP_FIELD_OPTIONS_MSS			equ	NETWORK_FRAME_TCP_FIELD_OPTIONS

;===============================================================================
; STRUKTURY
;===============================================================================
struc	KERNEL_STRUCTURE_GDT
	.null				resb	8
	.cs_ring0			resb	8
	.ds_ring0			resb	8
	.cs_ring3			resb	8
	.ds_ring3			resb	8
	.tss				resb	8
	.SIZE:
endstruc

struc	KERNEL_STRUCTURE_GDT_OR_IDT_HEADER
	.limit				resb	2
	.address			resb	8
endstruc

struc	KERNEL_STRUCTURE_BLOCK
	.data				resb	KERNEL_PAGE_SIZE_byte - QWORD_SIZE_byte
	.link				resb	QWORD_SIZE_byte	; wskaźnik do następnego bloku danych
	.SIZE:
endstruc

struc	KERNEL_STRUCTURE_TASK
	.pid				resb	8
	.cr3				resb	8
	.rsp				resb	8
	.flags				resb	2
	.length				resb	1
	.name				resb	255
	.SIZE:
endstruc

struc	NETWORK_STRUCTURE_MAC
	.0	resb	1
	.1	resb	1
	.2	resb	1
	.3	resb	1
	.4	resb	1
	.5	resb	1
endstruc
